spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mariadb://db:3306/appdb?useUnicode=true&characterEncoding=utf8}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.mariadb.jdbc.Driver}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_ID}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_SECRET}
            client-authentication-method: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_AUTHENTICATION_METHOD:client_secret_post}

app:
  jwt:
    secret: ${APP_JWT_SECRET}
    access-exp-seconds: ${APP_JWT_ACCESS_EXP_SECONDS:1800}
    refresh-exp-seconds: ${APP_JWT_REFRESH_EXP_SECONDS:1209600}

  frontend-url: ${APP_FRONTEND_URL:https://www.esjh.shop}

  cookie:
    secure: true
    same-site: None
    domain: ${APP_COOKIE_DOMAIN:}