package shop.esjh.memoryjar.enums.ai;

/** 투입구의 시각적 모양이다. 기존 종류는 3.5:1 경계를 유지하며 V43 자유형만 정사각 도면을 쓴다. */
public enum JarSlotStyle {
    CAPSULE, RECTANGLE, OVAL, METAL, WOOD, PIXEL,
    BRASS, ROSE_GOLD, OBSIDIAN, PEARL, PORCELAIN, LEATHER,
    LEAF, BAMBOO, BLOSSOM, PAW, SHELL, RIPPLE,
    STARLIGHT, MOONLIGHT, AURORA, CRYSTAL, RIBBON, KEYHOLE,
    BLOSSOM_GATE, HEART_GATE, PAW_GATE, BUTTERFLY_GATE,
    LEAF_GATE, SHELL_GATE, DROP_GATE, CLOUD_GATE,
    STAR_GATE, MOON_GATE, CRYSTAL_GATE, PLANET_GATE,
    RIBBON_GATE, KEY_GATE, SUN_GATE, SNOWFLAKE_GATE,
    TULIP_GATE, DAISY_GATE, LOTUS_GATE, CLOVER_GATE,
    CROWN_GATE, WING_GATE, PORTAL_GATE, LANTERN_GATE,
    CAT_GATE, BUNNY_GATE, BEAR_GATE, FOX_GATE, PANDA_GATE, KOALA_GATE,
    OWL_GATE, WHALE_GATE, FISH_GATE, DUCK_GATE, HEDGEHOG_GATE, DINO_GATE,
    WAVE_GATE, ANCHOR_GATE, CORAL_GATE, JELLY_GATE, SEAHORSE_GATE, TURTLE_GATE,
    DOLPHIN_GATE, STARFISH_GATE, OCTOPUS_GATE, PEARL_GATE, SAIL_GATE, CONCH_GATE,
    ORBIT_GATE, COMET_GATE, UFO_GATE, ROCKET_GATE, ECLIPSE_GATE, GALAXY_GATE,
    NOVA_GATE, METEOR_GATE, SATELLITE_GATE, ASTRO_GATE, CONSTELLATION_GATE, AURORA_GATE,
    DONUT_GATE, CUPCAKE_GATE, ICECREAM_GATE, CANDY_GATE, COOKIE_GATE, MACARON_GATE,
    CAKE_GATE, CHERRY_GATE, STRAWBERRY_GATE, PEACH_GATE, PUDDING_GATE, TEACUP_GATE,
    CAMERA_GATE, BOOK_GATE, MUSIC_GATE, PIANO_GATE, GUITAR_GATE, PALETTE_GATE,
    ENVELOPE_GATE, UMBRELLA_GATE, BALLOON_GATE, PUZZLE_GATE, GAMEPAD_GATE, TICKET_GATE,
    CIRCLE_GATE, TRIANGLE_GATE, DIAMOND_GATE, HEX_GATE, OCTAGON_GATE, ARCH_GATE,
    FAN_GATE, SPIRAL_GATE, INFINITY_GATE, KITE_GATE, PRISM_GATE, ROSETTE_GATE,
    MITTEN_GATE, BABY_SOCK_GATE, SCARF_GATE, BOWTIE_GATE, BABY_BIB_GATE, CUSHION_GATE,
    POMPOM_GATE, SLIPPER_GATE, BUTTON_GATE, POUCH_GATE, HEART_PATCH_GATE, QUILT_GATE,
    LADYBUG_GATE, SNAIL_GATE, SPROUT_GATE, WATERING_CAN_GATE, TOADSTOOL_GATE, ACORN_GATE,
    GARDEN_HOUSE_GATE, BEE_GATE, APPLE_GATE, CARROT_GATE, SUNFLOWER_GATE, GARDEN_SIGN_GATE,
    TOY_DUCK_GATE, ROCKING_HORSE_GATE, TEDDY_TOY_GATE, TOY_BALL_GATE, TOY_TRAIN_GATE, TOY_BLOCK_GATE,
    TOY_ROBOT_GATE, PINWHEEL_GATE, TOY_DRUM_GATE, MUSIC_BOX_GATE, SNOW_GLOBE_GATE, TOY_SAIL_GATE;

    private static final java.math.BigDecimal LEGACY_ASPECT_RATIO = new java.math.BigDecimal("3.5");

    /** V43 이후 자유형(_GATE)은 정사각 도면이다. V42까지의 ID는 기존 3.5:1 경계를 유지한다. */
    public java.math.BigDecimal aspectRatio() {
        return name().endsWith("_GATE") ? java.math.BigDecimal.ONE : LEGACY_ASPECT_RATIO;
    }

    /** 새 필드가 없는 기존 클라이언트·데이터는 원래 둥근 투입구를 유지한다. */
    public static JarSlotStyle orDefault(JarSlotStyle style) {
        return style == null ? CAPSULE : style;
    }
}
