ALTER TABLE members
    ADD COLUMN updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    ADD COLUMN deleted_at DATETIME(6) NULL;

ALTER TABLE refresh_tokens
    ADD COLUMN updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    ADD COLUMN deleted_at DATETIME(6) NULL;