-- 자유형은 새 ID로 저장한다. 이전 24종의 모양·좌표·사진·기본값은 재해석하거나 갱신하지 않는다.
ALTER TABLE jar_design_drafts
    DROP CONSTRAINT chk_draft_slot_style,
    ADD CONSTRAINT chk_draft_slot_style CHECK (slot_style IN (
        'CAPSULE','RECTANGLE','OVAL','METAL','WOOD','PIXEL',
        'BRASS','ROSE_GOLD','OBSIDIAN','PEARL','PORCELAIN','LEATHER',
        'LEAF','BAMBOO','BLOSSOM','PAW','SHELL','RIPPLE',
        'STARLIGHT','MOONLIGHT','AURORA','CRYSTAL','RIBBON','KEYHOLE',
        'BLOSSOM_GATE','HEART_GATE','PAW_GATE','BUTTERFLY_GATE',
        'LEAF_GATE','SHELL_GATE','DROP_GATE','CLOUD_GATE',
        'STAR_GATE','MOON_GATE','CRYSTAL_GATE','PLANET_GATE',
        'RIBBON_GATE','KEY_GATE','SUN_GATE','SNOWFLAKE_GATE'));

ALTER TABLE jar_designs
    DROP CONSTRAINT chk_design_slot_style,
    ADD CONSTRAINT chk_design_slot_style CHECK (slot_style IN (
        'CAPSULE','RECTANGLE','OVAL','METAL','WOOD','PIXEL',
        'BRASS','ROSE_GOLD','OBSIDIAN','PEARL','PORCELAIN','LEATHER',
        'LEAF','BAMBOO','BLOSSOM','PAW','SHELL','RIPPLE',
        'STARLIGHT','MOONLIGHT','AURORA','CRYSTAL','RIBBON','KEYHOLE',
        'BLOSSOM_GATE','HEART_GATE','PAW_GATE','BUTTERFLY_GATE',
        'LEAF_GATE','SHELL_GATE','DROP_GATE','CLOUD_GATE',
        'STAR_GATE','MOON_GATE','CRYSTAL_GATE','PLANET_GATE',
        'RIBBON_GATE','KEY_GATE','SUN_GATE','SNOWFLAKE_GATE'));
