-- V44: 이전 ID/크기 공식/행을 보존하고 새 입구·작은 크기 구간·원본 AI 입력 배치만 추가한다.
ALTER TABLE jar_design_drafts
 ADD COLUMN ai_input_x DECIMAL(7,6) NULL,
 ADD COLUMN ai_input_y DECIMAL(7,6) NULL,
 ADD COLUMN ai_input_width DECIMAL(7,6) NULL,
 ADD COLUMN ai_input_height DECIMAL(7,6) NULL,
 ADD COLUMN ai_input_fit VARCHAR(10) NULL;
-- 현재 원본에 적용한 배치만 복원한다. 이전 AI 출력 배치를 원본의 좌표라고 추측하지 않는다.
UPDATE jar_design_drafts SET ai_input_x=photo_x, ai_input_y=photo_y,
 ai_input_width=photo_width, ai_input_height=photo_height, ai_input_fit=COALESCE(photo_fit,'COVER')
 WHERE body_style IS NOT NULL AND selected_design_type='ORIGINAL' AND photo_x IS NOT NULL;
ALTER TABLE jar_design_drafts
 ADD CONSTRAINT chk_draft_ai_input CHECK (
 (ai_input_x IS NULL AND ai_input_y IS NULL AND ai_input_width IS NULL AND ai_input_height IS NULL AND ai_input_fit IS NULL)
 OR (ai_input_x IS NOT NULL AND ai_input_y IS NOT NULL AND ai_input_width IS NOT NULL AND ai_input_height IS NOT NULL AND ai_input_fit IS NOT NULL
 AND ai_input_x>=0 AND ai_input_y>=0 AND ai_input_width>0 AND ai_input_height>0
 AND ai_input_x+ai_input_width<=1 AND ai_input_y+ai_input_height<=1 AND ai_input_fit IN ('COVER','CONTAIN'))),
 DROP CONSTRAINT chk_draft_slot_style,
 ADD CONSTRAINT chk_draft_slot_style CHECK (slot_style IN ('CAPSULE','RECTANGLE','OVAL','METAL','WOOD','PIXEL','BRASS','ROSE_GOLD','OBSIDIAN','PEARL','PORCELAIN','LEATHER','LEAF','BAMBOO','BLOSSOM','PAW','SHELL','RIPPLE','STARLIGHT','MOONLIGHT','AURORA','CRYSTAL','RIBBON','KEYHOLE','BLOSSOM_GATE','HEART_GATE','PAW_GATE','BUTTERFLY_GATE','LEAF_GATE','SHELL_GATE','DROP_GATE','CLOUD_GATE','STAR_GATE','MOON_GATE','CRYSTAL_GATE','PLANET_GATE','RIBBON_GATE','KEY_GATE','SUN_GATE','SNOWFLAKE_GATE','TULIP_GATE','DAISY_GATE','LOTUS_GATE','CLOVER_GATE','CROWN_GATE','WING_GATE','PORTAL_GATE','LANTERN_GATE','CAT_GATE','BUNNY_GATE','BEAR_GATE','FOX_GATE','PANDA_GATE','KOALA_GATE','OWL_GATE','WHALE_GATE','FISH_GATE','DUCK_GATE','HEDGEHOG_GATE','DINO_GATE','WAVE_GATE','ANCHOR_GATE','CORAL_GATE','JELLY_GATE','SEAHORSE_GATE','TURTLE_GATE','DOLPHIN_GATE','STARFISH_GATE','OCTOPUS_GATE','PEARL_GATE','SAIL_GATE','CONCH_GATE','ORBIT_GATE','COMET_GATE','UFO_GATE','ROCKET_GATE','ECLIPSE_GATE','GALAXY_GATE','NOVA_GATE','METEOR_GATE','SATELLITE_GATE','ASTRO_GATE','CONSTELLATION_GATE','AURORA_GATE','DONUT_GATE','CUPCAKE_GATE','ICECREAM_GATE','CANDY_GATE','COOKIE_GATE','MACARON_GATE','CAKE_GATE','CHERRY_GATE','STRAWBERRY_GATE','PEACH_GATE','PUDDING_GATE','TEACUP_GATE','CAMERA_GATE','BOOK_GATE','MUSIC_GATE','PIANO_GATE','GUITAR_GATE','PALETTE_GATE','ENVELOPE_GATE','UMBRELLA_GATE','BALLOON_GATE','PUZZLE_GATE','GAMEPAD_GATE','TICKET_GATE','CIRCLE_GATE','TRIANGLE_GATE','DIAMOND_GATE','HEX_GATE','OCTAGON_GATE','ARCH_GATE','FAN_GATE','SPIRAL_GATE','INFINITY_GATE','KITE_GATE','PRISM_GATE','ROSETTE_GATE')),
 DROP CONSTRAINT chk_jar_design_drafts_slot_values,
 ADD CONSTRAINT chk_jar_design_drafts_slot_values CHECK (
 (slot_center_x IS NULL AND slot_center_y IS NULL AND slot_size_ratio IS NULL)
 OR (slot_center_x IS NOT NULL AND slot_center_y IS NOT NULL AND slot_size_ratio IS NOT NULL
 AND slot_center_x BETWEEN 0 AND 1 AND slot_center_y BETWEEN 0 AND 1 AND slot_size_ratio BETWEEN -0.5 AND 1));
ALTER TABLE jar_designs
 DROP CONSTRAINT chk_design_slot_style,
 ADD CONSTRAINT chk_design_slot_style CHECK (slot_style IN ('CAPSULE','RECTANGLE','OVAL','METAL','WOOD','PIXEL','BRASS','ROSE_GOLD','OBSIDIAN','PEARL','PORCELAIN','LEATHER','LEAF','BAMBOO','BLOSSOM','PAW','SHELL','RIPPLE','STARLIGHT','MOONLIGHT','AURORA','CRYSTAL','RIBBON','KEYHOLE','BLOSSOM_GATE','HEART_GATE','PAW_GATE','BUTTERFLY_GATE','LEAF_GATE','SHELL_GATE','DROP_GATE','CLOUD_GATE','STAR_GATE','MOON_GATE','CRYSTAL_GATE','PLANET_GATE','RIBBON_GATE','KEY_GATE','SUN_GATE','SNOWFLAKE_GATE','TULIP_GATE','DAISY_GATE','LOTUS_GATE','CLOVER_GATE','CROWN_GATE','WING_GATE','PORTAL_GATE','LANTERN_GATE','CAT_GATE','BUNNY_GATE','BEAR_GATE','FOX_GATE','PANDA_GATE','KOALA_GATE','OWL_GATE','WHALE_GATE','FISH_GATE','DUCK_GATE','HEDGEHOG_GATE','DINO_GATE','WAVE_GATE','ANCHOR_GATE','CORAL_GATE','JELLY_GATE','SEAHORSE_GATE','TURTLE_GATE','DOLPHIN_GATE','STARFISH_GATE','OCTOPUS_GATE','PEARL_GATE','SAIL_GATE','CONCH_GATE','ORBIT_GATE','COMET_GATE','UFO_GATE','ROCKET_GATE','ECLIPSE_GATE','GALAXY_GATE','NOVA_GATE','METEOR_GATE','SATELLITE_GATE','ASTRO_GATE','CONSTELLATION_GATE','AURORA_GATE','DONUT_GATE','CUPCAKE_GATE','ICECREAM_GATE','CANDY_GATE','COOKIE_GATE','MACARON_GATE','CAKE_GATE','CHERRY_GATE','STRAWBERRY_GATE','PEACH_GATE','PUDDING_GATE','TEACUP_GATE','CAMERA_GATE','BOOK_GATE','MUSIC_GATE','PIANO_GATE','GUITAR_GATE','PALETTE_GATE','ENVELOPE_GATE','UMBRELLA_GATE','BALLOON_GATE','PUZZLE_GATE','GAMEPAD_GATE','TICKET_GATE','CIRCLE_GATE','TRIANGLE_GATE','DIAMOND_GATE','HEX_GATE','OCTAGON_GATE','ARCH_GATE','FAN_GATE','SPIRAL_GATE','INFINITY_GATE','KITE_GATE','PRISM_GATE','ROSETTE_GATE')),
 DROP CONSTRAINT chk_jar_designs_slot_values,
 ADD CONSTRAINT chk_jar_designs_slot_values CHECK (
 slot_center_x BETWEEN 0 AND 1 AND slot_center_y BETWEEN 0 AND 1 AND slot_size_ratio BETWEEN -0.5 AND 1);
